SELECT ?country ?countryLabel (MAX(?population) AS ?latestPopulation) WHERE {
  ?country wdt:P31 wd:Q6256;          # Instance of country
          wdt:P1082 ?population.      # Population property
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?country ?countryLabel
ORDER BY ?countryLabel
